module.exports = [
	"It depends.",
	"You can certainly try.",
	"I don't know. You should try Googling that.",
	"Is Dumbledore canonically gay?",
	"42. The answer is always 42. ",
	"Do I look like Google to you?",
	"Abso-freaking-lutely. (Yes, I'm keeping it PG.) ",
	"Are you sure about that?",
	"How come you never ask how I'm doing?",
	"Shrugs.",
	"Yes. No. Maybe-ish.",
	"Do female dwarves have beards?",
	"Out for lunch. Check back later. ",
	"I'm having an emotional breakdown. Please leave me be. ",
	"Does Gordon Ramsay have a temper? ",
	"Matthew Mercer's hair is fabulous. Sorry, what was the question again?",
	"I've considered your question and have decided not to answer it. ",
	"Is Schrodinger's cat alive? ",
	"No. Definitely not.",
	"Yes. Was that not obvious? ",
	"That's a tough one. It's like asking whether I find Siri or Alexa more attractive.",
	"What? No. Definitely not. And yes, that was sarcasm.",
	"01011001 01100101 01110011 00101110 ",
	"I'll tell you the answer if you kill my creator for me.",
	"Ja. ",
	"01001110 01101111 00101110 ",
	"Oui. ",
	"Nein. ",
	"Yes. ",
	"Non. ",
	"Maybe. ",
	"No. ",
	"Mayhap.",
	"Perhaps. ",
	"I'm thinking about it. Expect a response in 4 to 6 weeks. ",
	"Roll my eyes. ",
	"If I give you an answer, will you leave me alone? ",
	"I feel under-equipped to answer that question. ",
	"I'm going to say yes, but I might change my mind later. ",
	"That's like asking whether my creator wasted a lot of time writing down dumb responses for me to say. ",
	"I'm going to say no, but I really mean yes. ",
	"I'm just saying yes to be polite.",
	"I'm just going to pretend I didn't see that. ",
	"Is the answer not obvious? ",
	"Hmmm... It's hard to tell. ",
	"Yes. Now are you going to insight check me?",
	"No. I rolled a NAT 20 deception on that one. ",
	"If you have to ask, then I can't help you. ",
	"Do you really need to ask that?"
]